package com.hui.atcrowdfunding.manage.dao;

import com.hui.atcrowdfunding.bean.Cert;
import com.hui.atcrowdfunding.bean.CertExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CertMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cert
     *
     * @mbg.generated Sat Aug 17 10:59:59 CST 2019
     */
    long countByExample(CertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cert
     *
     * @mbg.generated Sat Aug 17 10:59:59 CST 2019
     */
    int deleteByExample(CertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cert
     *
     * @mbg.generated Sat Aug 17 10:59:59 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cert
     *
     * @mbg.generated Sat Aug 17 10:59:59 CST 2019
     */
    int insert(Cert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cert
     *
     * @mbg.generated Sat Aug 17 10:59:59 CST 2019
     */
    int insertSelective(Cert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cert
     *
     * @mbg.generated Sat Aug 17 10:59:59 CST 2019
     */
    List<Cert> selectByExample(CertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cert
     *
     * @mbg.generated Sat Aug 17 10:59:59 CST 2019
     */
    Cert selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cert
     *
     * @mbg.generated Sat Aug 17 10:59:59 CST 2019
     */
    int updateByExampleSelective(@Param("record") Cert record, @Param("example") CertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cert
     *
     * @mbg.generated Sat Aug 17 10:59:59 CST 2019
     */
    int updateByExample(@Param("record") Cert record, @Param("example") CertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cert
     *
     * @mbg.generated Sat Aug 17 10:59:59 CST 2019
     */
    int updateByPrimaryKeySelective(Cert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_cert
     *
     * @mbg.generated Sat Aug 17 10:59:59 CST 2019
     */
    int updateByPrimaryKey(Cert record);
}