package com.hui.atcrowdfunding.manage.dao;

import com.hui.atcrowdfunding.bean.ParamExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param
     *
     * @mbg.generated Sat Aug 17 10:59:59 CST 2019
     */
    long countByExample(ParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param
     *
     * @mbg.generated Sat Aug 17 10:59:59 CST 2019
     */
    int deleteByExample(ParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param
     *
     * @mbg.generated Sat Aug 17 10:59:59 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param
     *
     * @mbg.generated Sat Aug 17 10:59:59 CST 2019
     */
    int insert(Param record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param
     *
     * @mbg.generated Sat Aug 17 10:59:59 CST 2019
     */
    int insertSelective(Param record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param
     *
     * @mbg.generated Sat Aug 17 10:59:59 CST 2019
     */
    List<Param> selectByExample(ParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param
     *
     * @mbg.generated Sat Aug 17 10:59:59 CST 2019
     */
    Param selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param
     *
     * @mbg.generated Sat Aug 17 10:59:59 CST 2019
     */
    int updateByExampleSelective(@Param("record") Param record, @Param("example") ParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param
     *
     * @mbg.generated Sat Aug 17 10:59:59 CST 2019
     */
    int updateByExample(@Param("record") Param record, @Param("example") ParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param
     *
     * @mbg.generated Sat Aug 17 10:59:59 CST 2019
     */
    int updateByPrimaryKeySelective(Param record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_param
     *
     * @mbg.generated Sat Aug 17 10:59:59 CST 2019
     */
    int updateByPrimaryKey(Param record);
}