package com.hui.atcrowdfunding.manage.dao;

import com.hui.atcrowdfunding.bean.Project_tag;
import com.hui.atcrowdfunding.bean.Project_tagExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Project_tagMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_tag
     *
     * @mbg.generated Sat Aug 17 10:59:59 CST 2019
     */
    long countByExample(Project_tagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_tag
     *
     * @mbg.generated Sat Aug 17 10:59:59 CST 2019
     */
    int deleteByExample(Project_tagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_tag
     *
     * @mbg.generated Sat Aug 17 10:59:59 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_tag
     *
     * @mbg.generated Sat Aug 17 10:59:59 CST 2019
     */
    int insert(Project_tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_tag
     *
     * @mbg.generated Sat Aug 17 10:59:59 CST 2019
     */
    int insertSelective(Project_tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_tag
     *
     * @mbg.generated Sat Aug 17 10:59:59 CST 2019
     */
    List<Project_tag> selectByExample(Project_tagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_tag
     *
     * @mbg.generated Sat Aug 17 10:59:59 CST 2019
     */
    Project_tag selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_tag
     *
     * @mbg.generated Sat Aug 17 10:59:59 CST 2019
     */
    int updateByExampleSelective(@Param("record") Project_tag record, @Param("example") Project_tagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_tag
     *
     * @mbg.generated Sat Aug 17 10:59:59 CST 2019
     */
    int updateByExample(@Param("record") Project_tag record, @Param("example") Project_tagExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_tag
     *
     * @mbg.generated Sat Aug 17 10:59:59 CST 2019
     */
    int updateByPrimaryKeySelective(Project_tag record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_tag
     *
     * @mbg.generated Sat Aug 17 10:59:59 CST 2019
     */
    int updateByPrimaryKey(Project_tag record);
}